apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
      annotations:
        diun.enable: "true"
    spec:
      volumes:
        - name: sonarr-nfs
          persistentVolumeClaim:
            claimName: sonarr-nfs
        - name: downloads
          persistentVolumeClaim:
            claimName: download
      containers:
        - name: sonarr
          image: ghcr.io/hotio/sonarr:release-4.0.9.2244
          env: 
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: UMASK
            value: "002"
          - name: TZ
            value: "Etc/UTC"
          ports:
            - containerPort: 8989
          volumeMounts:
            - name: sonarr-nfs
              mountPath: /config
            - name: downloads
              mountPath: /data
      nodeSelector:
          pvpn: "true"
      tolerations:
          - key: "network"
            operator: "Equal"
            value: "pvpn"
            effect: "NoSchedule"