apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - namespace.yml
  - pv.yml
  - pvc.yml
  - pv-download.yml
  - pvc-download.yml
  - deployment.yml
  - service.yml
#  - ingress.yml
