apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-nfs
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteOnce # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 10Gi # volume size requested
