apiVersion: v1
kind: Service
metadata:
  name: browser
  namespace: browser
  labels:
    app: browser
spec:
  type: LoadBalencer
  ports:
    - port: 52000
      targetPort: 52000
      protocol: UDP
  selector:
    app: browser
