apiVersion: v1
kind: Service
metadata:
  name: browser-webrtc
  namespace: browser
  labels:
    app: browser-webrtc
spec:
  type: LoadBalancer
  ports:
    - port: 52000
      targetPort: 52000
      protocol: UDP
    - port: 52001
      targetPort: 52001
      protocol: UDP
  selector:
    app: browser
