---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: foo
  namespace: default
spec:
  encryptedData:
    password: AgDFVSpRZ0arcU2fMkM8MZTECnuF1WfhamzeublqCMNQcSGXKvOCGiFOvOY3MSjNQQVCkgMVlJSvbdYrrhwXcL7iw7W0xCj7Bj9FDY38QG66g54la8sYEFGzt1zwi7WdGcwh2Wd+kCaMvRK8Iu5PVkaOelBet/cBdGJXsCvjuFrXaUIg/51l2o+vFVucGwFKSUIsP6MAXgue8vW3ZLahrnPI0NZqMhfKPf9oYmhNw104P8wkAaBew3ap8u/jrZ5iyPZgGCfjZ43XNtvwLAB/NlNyJoFoym/X9AiRRetfFM4sRXi0qeY/Tzq9JI33yOOnBigR/ualPdRaUKpY9eCbTWV6VQ4kqsRpjGxYzxLUGSofqfO+rdhEoLc45IMJY+M2JZ7/iaqKP7kU3mSRiyoiSa0sb46ei8wvYs3yKrNuMoM6j2eZwvtbztSNyz8oONvLXPIpvoZkoBBW70pydSjLKTY+0u0rzvJ8fYqGfQ+3r8ZroFXH2qbUA+pc65jfyS4YEBuY8XX+xYFyi5oojzBAKRvd0+cKlwFK0czyjhPIH8GDrZl3fo8cjsxJo3c84NpJrPH28wrWWwLFXP0dmTwFgt1WHrABdZNd1KhGxbjV4inkChKr2TxdEhLBWXQWeBMYqwz+phSkbcsIuSKobR0Cx9uvz/EEsMIIGuGIxvA8CRjvZ9akQaFRf2YINF2koVh3DmNmbByY3neu1w==
    user: AgBfOjceIaESk0nrraTP8unpBfmyvagPFmmgCEtAlNFHdBy+mtN8MH9faNwW83Qv1FoCCcwuvtDu66nvWP5mJQJLd7dxn6TP1ScoVKq02exprIV67rAi5AoKJBMoe6P7fumlPEGbj8nIH2zccvTJL4H4AVd6phw7Q/pfffMrVJ9GNu/8mDLHG3NRVaQEmRW23pH+3lSVFxhZDPfZFQPUWls7mdZ9dvF9vE4FyOMCHwu+FCYZgepjKs4SP6TLYQIqLuJ6KTsCvv9iWA3cNJaA3xTIVuRarTNq0RnHdEbIC1UiiyJnZvILm1vBFZDnyeFkAiGF00TjRuFRLebu0aOqVPpkXc9m31X6YXncD1z0GQHim4NYn/l1v13UgRJaLt8cARG1jfBVagDHSch+KcXxczqlCBpuXoCrqex/BZl/DaaVxivIJgX8Hc1iP9rgg9JP7RVzmqadbUBz6ZXiZvkSwivyTRrBC3mAdXa3CSzSQS4176RO8OWWVjE7fWeLR3TCxHU43qIhGgVoAGahfm121uvbVSHjMz27Uq+y2aGa3KS3rZXiQwB1bkU5T7O3gPKksAQ0EMGVrLLS6JYaOla5+uMUltmkSMn3/Pf+SAn0FQpsVYqp1z0o1MjnuuzfaeJha8QwAquyiPlKyLgMvGpbsqJQ1Liavxgm2mN+IT/oB49WTCXoFFlXd99LQun3/ah6Q7bP+UocDQ==
  template:
    metadata:
      creationTimestamp: null
      name: foo
      namespace: default
