apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openweb-data-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-cephfs