apiVersion: v1
kind: Service
metadata:
  name: memos
  namespace: memos
spec:
  ports:
  - name: http
    port: 7745
    protocol: TCP
    targetPort: http
  selector:
    app: memos
  type: ClusterIP
  