apiVersion: v1
kind: PersistentVolume
metadata:
  name: download-volume
  namespace: media
spec:
  capacity:
    storage: 100Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteMany # Access modes are defined below
  storageClassName: slow
  nfs:
    server: truenas.home # Please change this to your NFS server
    path: /mnt/tank/kubestore/download # Please change this to the relevant share
