apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download
  namespace: media
spec:
  storageClassName: slow
  accessModes:
    - ReadWriteMany # Access modes for volumes is defined under Persistent Volumes
  resources:
    requests:
      storage: 100Gi # volume size requested
