apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: duin-data-claim
  namespace: duin
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-cephfs