apiVersion: v1
kind: PersistentVolume
metadata:
  name: sd-volume
spec:
  capacity:
    storage: 10Gi # This size is used to match a volume to a tenents claim
  accessModes:
    - ReadWriteOnce # Access modes are defined below
  storageClassName: slow
  persistentVolumeReclaimPolicy: Recycle # Reclaim policies are defined below
  nfs:
    server: truenas.home # Please change this to your NFS server
    path: /mnt/tank/kubestore/sd # Please change this to the relevant share
