apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshtastic
  labels:
    app: meshtastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meshtastic
  template:
    metadata:
      labels:
        app: meshtastic
      annotations:
        diun.enable: "true"
    spec:
      containers:
        - name: meshtastic
          image: ghcr.io/meshtastic/web:633b99d6b26053b54135dc70e11f77ded1cef57f
          ports:
            - containerPort: 8080
      nodeSelector:
        kubernetes.io/arch: arm64