apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
  labels:
    app: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
      annotations:
        diun.enable: "true"
    spec:
      volumes:
        - name: mealie-nfs
          persistentVolumeClaim:
            claimName: mealie-nfs
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v2.5.0
          env:
          - name: BASE_URL
            value: "https://mealie.kube.home"
          - name: OPENAI_BASE_URL
            value: "http://ollama.kube.home:80/v1"
          - name: OPENAI_API_KEY
            value: foobar
          - name: OPENAI_MODEL
            value: llama3.1:8b
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: mealie-nfs
              mountPath: /app/data
      nodeSelector:
        workload: general