apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cephfs-uptime-data-claim
  #namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: k8s-cephfs