apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: awx
  namespace: awx
spec:
  interval: 5m
  chart:
    spec:
      chart: awx-operator
      version: '2.7.2'
      sourceRef:
        kind: HelmRepository
        name: awx
        namespace: awx
      interval: 1m